apiVersion: v1
kind: Service
metadata:
  name: SERVICE_NAME
spec:
  ports:
    - port: 8080
      targetPort: PORT
---
kind: Endpoints
apiVersion: v1
metadata:
  name: SERVICE_NAME
subsets:
  - addresses:
      - ip: 192.168.65.2
    ports:
      - port: PORT
